import Head from "next/head";

import Navbar from "../components/navbar/navbar";
import Banner from "../components/banner/banner";
import SectionCards from "../components/card/section-cards";

import { getPopularVideos, getVideos } from "../lib/videos";

import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  // all video content
  const disneyVideos = await getVideos("disney trailer");
  const travelVideos = await getVideos("travel trailer");
  const productivityVideos = await getVideos("productivity trailer");
  const popularVideos = await getPopularVideos();
  return {
    props: { disneyVideos, travelVideos, productivityVideos, popularVideos },
  };
}

export default function Home({
  disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar username="zahrajiryaee77@gmail.com" />

        <Banner
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
