import Head from "next/head";

import Navbar from "../components/navbar/navbar";
import Banner from "../components/banner/banner";
import SectionCards from "../components/card/section-cards";

import styles from "../styles/Home.module.css";

export default function Home() {
  const disneyVideos = [
    { imgUrl: "/static/clifford.webp" },
    { imgUrl: "/static/clifford.webp" },
    { imgUrl: "/static/clifford.webp" },
    { imgUrl: "/static/clifford.webp" },
    { imgUrl: "/static/clifford.webp" },
    { imgUrl: "/static/clifford.webp" },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="zahrajiryaee77@gmail.com" />

      <Banner
        title="Clifford the red dog"
        subTitle="a very cute dog"
        imgUrl="/static/clifford.webp"
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
        <SectionCards
          title="Productivity"
          videos={disneyVideos}
          size="medium"
        />
      </div>
    </div>
  );
}
